name = "chentik-web"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js/index.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true
